server:
  port: 18008
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: SAA-09Text2image

  ai:
    dashscope:
      api-key: ${aliQwen-api}

    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      connect-timeout: 3
      timeout: 2
      password: root@000
      username: default

