server:
  port: 8005
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  application:
    name: SAA-05Prompt

  ai:
    dashscope:
      api-key: ${aliQwen-api}

    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b

