server:
  port: 18015
  servlet:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
spring:
  application:
    name: SAA-15LocalMcpClient
  ai:
    dashscope:
      api-key: ${aliQwen-api}
      chat:
        options:
          model: qwen3-max

    mcp:
      client:
        type: async
        request-timeout: 60s
        toolcallback:
          enabled: true
        sse:
          connections:
            mcp-server1.url: http://localhost:18014

